### ISSUE TITLE
Syntax Error @ board:

### ISSUE THREAD

**Issue by epe** [maxammann/trello-to-deck#12]
Hi,
Nice tool, I was excited to find it! I tried using it last night, but got 2 Errors. I'm not a python genius, but usually get around using pip, python and scripts, but I didnt manage to get around these errors:

Error #1 
  File "./scripts/trello-to-deck", line 32
SyntaxError: Non-ASCII character '\xe2' in file ./scripts/trello-to-deck on line 32, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Error #2 
user@shell$ python scripts/trello-to-deck
  File "scripts/trello-to-deck", line 36
    board: Board = to_board(
         ^
SyntaxError: invalid syntax

Running on my notebook with elementary Linux and the following versions:
* Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2
*uname -a: Linux topaz 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Am I missing a pip/python dependency? 
thanks for your recommendation!

**Comment by maxammann** [comment]
The script only works with python3. So try to run the following: 

```
pip3 install .
trello-to-deck
```

**Comment by epe** [comment]
Hi Max, I did that, failed, so tried again starting from scrap: 
git clone, pip3 install .  
Is there something more I need to do? 

What makes your system start the command without calling python3 or python3.6? Do you copy the files to a /usr/bin dir? or have some magic env variable?
trello_to_deck
trello_to_deck: Befehl nicht gefunden.


python3.6 ./scripts/trello-to-deck 
Traceback (most recent call last):
  File "./scripts/trello-to-deck", line 7, in <module>
    from trello_to_deck.trello import to_board, Board
  File "/home/eric/.local/lib/python3.6/site-packages/trello_to_deck/trello.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by chaudum** [comment]
> Hi Max, I did that, failed, so tried again starting from scrap:
> git clone, pip3 install .
> Is there something more I need to do?

No, installing using pip3 should be sufficient.
What does `pip3 --version` say about the version?

> 
> What makes your system start the command without calling python3 or python3.6? Do you copy the files to a /usr/bin dir? or have some magic env variable?

When you install via `pip3` the package is installed into the site-packages of the Python version of `pip3`.

> trello_to_deck
> trello_to_deck: Befehl nicht gefunden.
> 
> python3.6 ./scripts/trello-to-deck
> Traceback (most recent call last):
> File "./scripts/trello-to-deck", line 7, in
> from trello_to_deck.trello import to_board, Board
> File "/home/eric/.local/lib/python3.6/site-packages/trello_to_deck/trello.py", line 1, in
> from dataclasses import dataclass
> ModuleNotFoundError: No module named 'dataclasses'

`dataclasses` are new in Python 3.7, see https://docs.python.org/3/library/dataclasses.html, but you're using Python 3.6.

**Comment by epe** [comment]
Ok, thanks to all. 

My experience - Maybe use this for documentation if it makes sense? 

On an average Ubuntu/Debian/Elementary Machine you would have to do: 


apt install python3.7
git clone git@github.com:maxammann/trello-to-deck.git
python3.7 -m pip install .
python3.7 scripts/trello-to-deck $input_json $nextcloud_instance $username $password

**Comment by maxammann** [comment]
Thanks for providing the solution :)
