### ISSUE TITLE
Nextcloud password requires escaping special characters

### ISSUE THREAD

**Issue by ghost** [maxammann/trello-to-deck#17]
When uploading a Trello board to a particular account I had trouble authenticating because special characters were not being escaped correctly. I had to add a backslash to each character to pass the authentication. Specifically the characters I escaped were `_`, `$`, `[` and `{` although I imagine that not all of these are causing the problem.

I'm not sure what common practice is with this but it should at least be covered in the README.

**Comment by maxammann** [comment]
I think the solution would be not to pass the password via command line parameters. That way it also isn't stored to the bash history.

Can you provide an example where you would have to escape a password? I think this is more of a bash/shell problem.

When putting a string into `"quotes"` you need to escape for example `$`. That is not need if you put it into `'quotes'`.

**Comment by maxammann** [comment]
I'm very sure this is related to bash/zsh and not a problem of this script, reopen if you think this is wrong.
