### ISSUE TITLE
Import Error with attachments

### ISSUE THREAD

**Issue by epe** [maxammann/trello-to-deck#20]
Just found another one with a board that had errors before. This one looks like this:
Not sure if it's the same as in #19 but if it is, than #19 doesnt seem to be solved yet.

		Ataching https://trello-attachments.s3.amazonaws.com/nnnnnnnnnnnnnnnnnnn.jpg to card NNNNNNN
		Ataching https://trello-attachments.s3.amazonaws.com/mmmmmmmmmmmm/MMMMMMMMM.jpg to card MMMMMMMMM
The response was: b'{"status":400,"message":"type must be provided"}'
Traceback (most recent call last):
  File "./bin/trello-to-deck/scripts/trello-to-deck", line 102, in <module>
    api.attachToCard(nextcloudBoardId, nextcloudStackId, nextcloudCardId, attachment.fileName, response.raw, attachment.mimeType)
  File "/home/eric/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 146, in attachToCard
    {"file": (fileName, fileObject, mimeType)},
  File "/home/eric/.local/lib/python3.7/site-packages/trello_to_deck/deck.py", line 44, in postFiles
    response.raise_for_status()
  File "/home/eric/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad request for url: https://WHATEVERHOST/index.php/apps/deck/api/v1.0/boards/37/stacks/97/cards/1426/attachments

**Comment by maxammann** [comment]
Which version of deck and nextcloud are you using?

**Comment by epe** [comment]
Nextcloud 20 and the latest Deck, just recently installed on armbian/helios64 device.


Am 30. November 2020 09:06:38 MEZ schrieb Max Ammann <notifications@github.com>:
>Which version of deck and nextcloud are you using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maxammann/trello-to-deck/issues/20#issuecomment-735624352

Freundliche Grüße
Eric Poscher-Mika
--
+43 699 11403480

**Comment by maxammann** [comment]
I think I need the exact version so we can be sure of it. I can not reproduce this with my nextcloud instance.

**Comment by maxammann** [comment]
Closing this as there was no progress in the past 20 days.
