### ISSUE TITLE
pip install with root privileges is required

### ISSUE THREAD

**Issue by nesnera** [maxammann/trello-to-deck#22]
The installation with the command `$ pip-3.7 install . --user` proceeds correctly, but the call ends with the error:
```
$ trello-to-deck .. ..
bash: /usr/local/bin/trello-to-deck: No such file or directory
```

**Comment by maxammann** [comment]
Thanks for the report! This seems like a bug indeed. Though I'm not sure why this happens.

**Comment by maxammann** [comment]
Unfortunately I can not reproduce this. The installation works for me fine aswell. I can only see the behavior you specified after uninstalling the package. Can you post the whole output of `pip-3.7 install . --user` and `pip-3.7 uninstall trello-to-deck`?

**Comment by maxammann** [comment]
Closing as there was no progress in the past month
