### ISSUE TITLE
Package as Nextcloud app

### ISSUE THREAD

**Issue by sunjam** [maxammann/trello-to-deck#23]
Hi, this is an amazing addition.  My request, which I understand might not be feasible, is to [package this for the app store](https://nextcloudappstore.readthedocs.io/en/latest/developer.html).  Thanks for considering and great work!

**Comment by maxammann** [comment]
I think that wont be possible. This tool is writting in python and uses the API. I think that the app store is only for php apps with run with the nextcloud stack.

I think it would be cool to feature this tool somewhere though. Like in the offical nextcloud deck readme.

**Comment by sunjam** [comment]
> I think it would be cool to feature this tool somewhere though. Like in the offical nextcloud deck readme.

Definitely would be an excellent thing to do for the [Email to Deck](https://github.com/putt1ck/mail2deck) app as well!

**Comment by maxammann** [comment]
@sunjam do you maybe want to create a PR here? https://github.com/nextcloud/deck 

I probably dont have the time in the next month.

**Comment by maxammann** [comment]
See https://github.com/nextcloud/deck/pull/3036

**Comment by maxammann** [comment]
Done: https://github.com/nextcloud/deck#3rd-party-integrations
