### ISSUE TITLE
File "./trello-to-deck", line 37

### ISSUE THREAD

**Issue by AndreasGrosz** [maxammann/trello-to-deck#28]
~/programme/trello-to-deck-main/scripts$ ./trello-to-deck trello.json http://192.168.188.50:8080/ andreas xxxxx

  File "./trello-to-deck", line 37

    board: Board = to_board(
         ^

SyntaxError: invalid syntax

This is what I got. Can not continue, need help.

**Comment by maxammann** [comment]
I edited your respinse because it included the password.

You have to install this repository as pip package first. Please see the README.

**Comment by maxammann** [comment]
If the issue persists, please reopen
